-- BUILD PRODUCT REPORT
--GATHER ESSENTIAL FIELDS SUCH AS PRODUC NAME , CATEGORY , SUBCATEGORY, COST
-- SEGMENT PRODUCT BY REVNUE  TO IDENTIFY HIGH PERFORMANECE , MID-RANGE AND  LOW PERFORMANCE


CREATE VIEW GOLD.PRODUCT_REPORT AS

WITH BASE_QUERRY AS(
SELECT 
S.ORDER_NUMBER,
S.ORDER_DATE,
S.CUSTOMER_KEY,
S.QUANTITY,
S.SALES,
P.[PRODUCT_KEY],
P.PRODUCT_NAME,
P.CATEGORY,
P.SUB_CATEGORY,
P.PRODUCT_COST
FROM GOLD_PRODUCT_DIM P
RIGHT JOIN GOLD.FACT_SALES S
ON P.PRODUCT_KEY=S.PRODUCT_KEY
)
--SELECT * FROM GOLD.FACT_SALES

--AGGREGATION
, AGGREGATION AS(
SELECT PRODUCT_KEY ,
PRODUCT_NAME,
CATEGORY,
SUB_CATEGORY,
PRODUCT_COST,
datediff(month, MIN(ORDER_DATE),MAX(ORDER_DATE)) AS LIFESPAN,
MAX(ORDER_DATE) AS LAST_ORDER_DATE,
COUNT(DISTINCT ORDER_NUMBER )AS TOTAL_ORDERS,
COUNT(DISTINCT CUSTOMER_KEY ) AS TOTAL_PRODUCT,
SUM(SALES)AS TOTAL_SALES,
SUM(QUANTITY) AS TOTAL_QUANTITY,
 ROUND(AVG(CAST (SALES AS FLOAT)/ COALESCE (QUANTITY,0)),1) AS AVG_SELLING_PRICE
FROM BASE_QUERRY
GROUP BY PRODUCT_KEY ,
PRODUCT_NAME,
CATEGORY,
SUB_CATEGORY,
PRODUCT_COST
)
--  create a final  report
SELECT 
	PRODUCT_KEY ,
	PRODUCT_NAME,
	CATEGORY,
	SUB_CATEGORY,
	PRODUCT_COST,
	 LIFESPAN,
	 CASE WHEN TOTAL_SALES>50000 THEN 'HIGH PERFORMANCE'
	 WHEN TOTAL_SALES>=10000 THEN 'MID PERFORMANCE'
	 ELSE 'LOW PERFORMANCE'
	 END AS PRODUCT_SEGMENT,
	 LAST_ORDER_DATE,
	 TOTAL_ORDERS,
	TOTAL_PRODUCT,
	TOTAL_SALES,
	 TOTAL_QUANTITY,
	AVG_SELLING_PRICE,
	--AVG MONTHLY REVENUE
	CASE  WHEN LIFESPAN=0 THEN TOTAL_SALES
	ELSE TOTAL_SALES/LIFESPAN
	END AS AVG_MONTHLY_REVENUE
FROM AGGREGATION
